# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  quick_colors: "" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 0 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 0 # for disable sidebar and sidebar button change to 0

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "Tudo"
      slug: "box-item"
      active: 1

    - name: "Trampos"
      slug: "f-work"
      active: 1

    - name: "Videos"
      slug: "f-video"
      active: 1

    - name: "Escrita"
      slug: "f-writing"
      active: 1

    - name: "Games"
      slug: "f-game"
      active: 1

    - name: "Audio"
      slug: "f-audio"
      active: 1

    - name: "Fotografias"
      slug: "f-gallery"
      active: 1

    - name: "Conte√∫do"
      slug: "f-content"
      active: 1